### ISSUE TITLE
Searching based on multiple skills

### ISSUE THREAD

**Issue by priyamshah0709** [yagmurbbayraktar/CSC510_Project2#2]

**Comment by priyamshah0709** [comment]
Split the input and search based on individual keywords and combine all the result. For eg: When input is "Pyhton, JAVA" first search based on python, than for JAVA and combine results from both.

**Comment by Nisanchhetri** [comment]
Completing first part. Also adding same features for multiple companies

**Comment by Nisanchhetri** [comment]
Added splitting input and search based on individual keywords and combine results for company and skills subsection. Improved index displaying format from 0 to 1.
